const express = require("express");
const multer = require("multer");
const {adminIn, } = require("../api/admin");
const {signup, signin} = require("../api/sign");
const comment = require("../api/comment");
const shopping = require("../api/shopping");
const {upload, } = require("../api/bigFile");
const session = require("./auth");
const perfect = require("../api/perfect");
const router = express.Router();
router.use(session);
router.post("/signup", signup);
router.post("/signin", signin);
router.post("/upload", multer().array("file"), upload);
router.post("/adminin", adminIn);
router.post("/shopping", multer().array(), shopping);
router.post("/comment", comment);
router.post("/perfect",  multer().array(), perfect);
module.exports = router;